CREATE DATABASE LIGHTCONTROLDB;

USE "LIGHTCONTROLDB";

CREATE TABLE ELECTRICITY_BILL
(
    READ_NUMBER INT NOT NULL,
    READ_DATE DATETIME NOT NULL,
    KW_MONTHLY_SPENT DECIMAL NOT NULL,
    BILL_VALUE DECIMAL(10,2) NOT NULL,
    PAY_DATE DATETIME NOT NULL,
    AVERAGE_CONSUMPTION DECIMAL(10,2) NOT NULL,
    BILLING_MONTH INT NOT NULL,
    BILLING_YEAR INT NOT NULL,
    CONSTRAINT PK_BILL PRIMARY KEY (BILLING_MONTH, BILLING_YEAR)
);